# Generated by Django 3.2 on 2024-07-05 10:20

from django.db import migrations, models
import django.db.models.deletion
import random


def forwards_func(apps, schema_editor):
    # Assign random worker to user
    Worker = apps.get_model("company", "Worker")
    User = apps.get_model("core", "User")

    workers_ids = Worker.objects.all().values_list("pk", flat=True)

    for instance in User.objects.all():
        random_worker = Worker.objects.get(pk=random.choice(workers_ids))
        instance.worker = random_worker
        instance.save(update_fields=["worker"])


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0009_alter_task_status"),
        ("core", "0003_auto_20240506_1430"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="company.worker",
            ),
        ),
        migrations.RunPython(code=forwards_func, reverse_code=reverse_func),
    ]
