# Generated by Django 3.2 on 2024-05-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_action_historylog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="action",
            options={"ordering": ["type"]},
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Nowe", "Nowe"),
                    ("W trakcie", "W trakcie"),
                    ("Porzucone", "Porzucone"),
                    ("Zakończone", "Zakończone"),
                ],
                default="Nowe",
                max_length=20,
            ),
        ),
    ]
