# Generated by Django 3.2 on 2024-06-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='maximum_expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
