# Generated by Django 3.2 on 2024-07-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_auto_20240613_1227"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Nowe", "Nowe"),
                    ("W trakcie", "W trakcie"),
                    ("Porzucone", "Porzucone"),
                    ("Zakończone", "Zakończone"),
                    ("Zamknięte", "Zamknięte"),
                ],
                default="Nowe",
                max_length=20,
            ),
        ),
    ]
